osx_image: xcode10.2
cache:
  - bundler: true
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle exec danger; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle; fi
jobs:
  include:
  - stage: Test
    name: "SwiftPM - Linux"
    os: linux
    sudo: required
    dist: trusty
    env:
      - SWIFT_VERSION=5.0
      - SWIFTENV_INSTALL="https://gist.githubusercontent.com/johnhammerlund/b4c3686e4270d463ef955c5a77f0b814/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh"
    install:
      - eval "$(curl -sL $SWIFTENV_INSTALL)"
    script:
      - rake test_spm
  - stage: Test
    name: "SwiftPM - macOS"
    os: osx
    script:
      - rake test_spm
  - stage: Test
    name: "iOS"
    os: osx
    sudo: required
    install:
      - eval "$(sudo mkdir /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\\ 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib)"
    script:
      - rake test_ios
  - stage: Test
    name: "macOS"
    os: osx
    script:
      - rake test_macos
  - stage: Test
    name: "tvOS"
    os: osx
    sudo: required
    install:
      - eval "$(sudo mkdir /Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS\\ 9.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib)"
    script:
      - rake test_tvos
  - stage: Test
    name: "watchOS"
    os: osx
    script:
      - rake test_watchos
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'Relay' -F main
