matrix:
  include:
    - os: osx
      osx_image: xcode10
      language: swift
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        SWIFT_VERSION=4.1
env:
  global:
    - SWIFTENV_INSTALL="https://gist.githubusercontent.com/johnhammerlund/b4c3686e4270d463ef955c5a77f0b814/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh"
cache:
  - bundler: true
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle exec danger; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL $SWIFTENV_INSTALL)"; fi
jobs:
  include:
  - stage: Cross-Platform Tests
    name: "SPM"
    script:
      - rake test_spm
  - stage: Cocoa Tests
    name: "iOS"
    os: osx
    script:
      - rake test_ios
  - stage: Cocoa Tests
    name: "macOS"
    os: osx
    script:
      - rake test_macos
  - stage: Cocoa Tests
    name: "tvOS"
    os: osx
    script:
      - rake test_tvos
  - stage: Cocoa Tests
    name: "watchOS"
    os: osx
    script:
      - rake test_watchos
