language: swift
osx_image: xcode10
cache:
- bundler: true
install:
- rake boot_simulators
- bundle install
- bundle exec danger
- brew update
- brew bundle
jobs:
  include:
  - stage: Test
    name: "SwiftPM"
    script:
    - rake test_spm
  - stage: Test
    name: "iOS"
    script:
    - rake test_ios
  - stage: Test
    name: "macOS"
    script:
    - rake test_macos
  - stage: Test
    name: "tvOS"
    script:
    - rake test_tvos
  - stage: Test
    name: "watchOS"
    script:
    - rake test_watchos
